name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
      
    - name: Build and Test Package
      run: swift test
      
    - name: Build App
      run: |
        cd OCPIValidatorApp
        xcodebuild -scheme OCPIValidatorApp -configuration Debug build

  lint:
    name: SwiftLint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: SwiftLint
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --strict

  deploy:
    name: Deploy
    needs: [test, lint]
    runs-on: macos-14
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Archive App
      run: |
        cd OCPIValidatorApp
        xcodebuild -scheme OCPIValidatorApp -configuration Release archive -archivePath OCPIValidatorApp.xcarchive
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: OCPIValidatorApp/OCPIValidatorApp.xcarchive/Products/Applications/OCPIValidatorApp.app 